/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ngo-mon.glb --transform --keepnames --types 
Files: public/models/ngo-mon.glb [289.09MB] > C:\Users\LENOVO\.gemini\antigravity\scratch\huevivu-nextjs\ngo-mon-transformed.glb [22.67MB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_node: THREE.Mesh
    mesh_node001: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    ['material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTF['animations']
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ngo-mon-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="mesh_node" geometry={nodes.mesh_node.geometry} material={materials.material} position={[0, 2.624, 0]} scale={8.609} />
      <mesh name="mesh_node001" geometry={nodes.mesh_node001.geometry} material={materials['material.001']} position={[4.637, 0, 4.394]} scale={[3.661, 2.826, 2.826]} />
    </group>
  )
}

useGLTF.preload('/ngo-mon-transformed.glb')
